[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"  # Skip the Next.js plugin since we're using static export
  FIREBASE_AUTH_DOMAIN = "b2bshowcase-199a8.firebaseapp.com"

# Handle all routes for client-side navigation
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Handle Firebase Authentication
[[redirects]]
  from = "/.auth/*"
  to = "https://b2bshowcase-199a8.firebaseapp.com/.auth/:splat"
  status = 200
  force = true

# Handle static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
